### ISSUE TITLE
Add docker hub image

### ISSUE THREAD

**Issue by leojonathanoh** [fcolista/apkfile#1]
Thank you for this useful utility. 😄 It can be very useful for cron scripts / daily builds that checks for updated alpine packages.

Because of this script's dependencies on `curl` and `html2text` utilities, it make sense to package this as a docker image. 

Will you be willing to publish an official docker image? I can contribute PRs to add CI files to automatically publish an image on every commit on `master` and `tags`.

**Comment by fcolista** [comment]
@leojonathanoh thanks for your nice words :)

A docker image exists:

https://hub.docker.com/repository/docker/fcolista/apkfile/general

Just go ahead and ```docker pull fcolista/apkfile:v0.04``` ;-)

**Comment by leojonathanoh** [comment]
oh thanks, that link requires a login, the repo is https://hub.docker.com/r/fcolista/apkfile/. I could use that image in the meantime 😄 

Guess the images were docker pushed manually. I was thinking of adding CI for automatic builds 😃

**Comment by fcolista** [comment]
Yup.
When I'll find some time, I would make it.
Thanks a lot!








Il giorno gio 29 giu 2023 alle ore 16:10 leo ***@***.***> ha
scritto:

**Comment by leojonathanoh** [comment]
Thank you 😺. I'll close this issue.
